### ISSUE TITLE
Ryacas version in `parse_lna_rates`

### ISSUE THREAD

**Issue by slwu89** [fintzij/stemr#2]
Hi, I noticed there are two calls to `Ryacas::Sym` in the function `parse_lna_rates` but the function `Sym` is from the now legacy Ryacas0 package (there's no function `Sym` in the current Ryacas package). 

See (legacy): https://r-cas.github.io/ryacas0/reference/Sym.html
current: https://r-cas.github.io/ryacas/reference/ysym.html

I didn't do a PR because I'm not sure which version you prefer to go with, but changing to `Ryacas0::Sym` made all the vignettes/code run fine for me.

**Comment by fintzij** [comment]
Hi Sean, thanks for digging into it. I guess either way would solve the annoying issue of having to install an old version of Ryacas. 

I guess I don't have a preference, but I also haven't been keeping up with updates to yacas since I first implemented this part of the stemr package, which at this point was several years ago. Perhaps there are merits to going with the current version if, e.g., it does a better job simplifying expressions. Do you know if this is the case?

**Comment by slwu89** [comment]
Unfortunately I don't use yacas for symbolic calculations, so I really don't know what the relative merits are. In any case to use the current version I substituted the calls to `Ryacas::ysym` and because the storage type is slightly different, I had to change the lines where derivatives of the rate functions are taken to coerce back to a string so `D` knows what to do with them as:

`derivatives[[t]][[s]] <- D(rate_syms[[t]], as.character(comp_syms[[s]]))`
`time_derivs[[t]] <- D(rate_syms[[t]], as.character(time_sym))`

Using the current version gives the same results on the stemr_sir vignette.

**Comment by fintzij** [comment]
Hi Sean, thanks again for the fix here. I just pushed an update to fix the issue.
